### ISSUE TITLE
Intervals of 45mins not being calculated properly

### ISSUE THREAD

**Issue by Yaajvin** [jannicz/appointment-picker#33]
When choosing an interval of 45mins, the time slots are not being calculated properly.
See screenshot provided.

![image](https://user-images.githubusercontent.com/61848013/154010493-a7ffc3be-45f0-4bfe-842a-52ca6d102c2a.png)
![image](https://user-images.githubusercontent.com/61848013/154010806-2780bdc4-0c69-4c87-a498-a1217383bb72.png)

It must be 10:00, 10:45, 11:30, 12:15, ... 
I have not tested for all different kind of intervals between 1-60, other intervals may not be calculated properly as well.

**Comment by jannicz** [comment]
Hi @Yaajvin, i had a look into it and you are right: the interval you want to have is not possible. The algorithm will always display the full next hour between interval 31 and 59. Now I remember that this was the requirement i had to meet back then. Changing it might break the functionality for other users, as they won't expect this change.

The problem is rather as a missing/wrong README because this limitation is not explained. I am sorry to disappoint you, but it works as initially designed.
